#! /usr/bin/env bash
~/depots/gcc-arm-none-eabi.old/install-native/bin/arm-none-eabi-gdb -ex "set target-charset ASCII" -ex "set print pretty on" -ex "set remotelogfile mri.log" -ex "target remote :3333" _build/*.out
